# MISSING VALUES OF CATAGORICAL AND NUMERICAL VALUES

## Random Imputation

In [2]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [4]:
# upload titanic dataset only use age, fare, survived
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', usecols=['Survived', 'Age', 'Fare'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [5]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [6]:
x = df.drop(columns='Survived')
y = df['Survived']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
x_train['age_imputed'] = x_train['Age']
x_test['age_imputed'] = x_test['Age']

In [9]:
x_train.head()

      Age     Fare  age_imputed
331  45.5  28.5000         45.5
733  23.0  13.0000         23.0
382  32.0   7.9250         32.0
704  26.0   7.8542         26.0
813   6.0  31.2750          6.0

In [10]:
x_test.head()

      Age     Fare  age_imputed
709   NaN  15.2458          NaN
439  31.0  10.5000         31.0
840  20.0   7.9250         20.0
720   6.0  33.0000          6.0
39   14.0  11.2417         14.0

TypeError: "value" parameter must be a scalar, dict or Series, but you passed a "ndarray"