# Feature Scaling

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# import libraries for model training
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Upload dataset

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head(5)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:

x_train, x_test, y_train, y_test = train_test_split(df[['Age', 'EstimatedSalary']], df['Purchased'], test_size=0.2, random_state=0)
x_train.shape, x_test.shape

((320, 2), (80, 2))

## StandartScaler

In [7]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# now set the scaler to the training data
scaler.fit(x_train)
# transform the training and testing data
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [9]:
scaler.mean_

array([3.8218750e+01, 6.9928125e+04])

In [10]:
train_df = pd.DataFrame(x_train_scaled, columns=['Age', 'EstimatedSalary'])
train_df.head(5)

        Age  EstimatedSalary
0  1.922950         2.146016
1  2.020161         0.378719
2 -1.382215        -0.432499
3 -1.187794        -1.011940
4  1.922950        -0.925024

In [14]:
pd.DataFrame(x_train_scaled, columns=['Age', 'EstimatedSalary']).describe().round(1)

         Age  EstimatedSalary
count  320.0            320.0
mean     0.0              0.0
std      1.0              1.0
min     -2.0             -1.6
25%     -0.8             -0.8
50%     -0.0             -0.0
75%      0.8              0.5
max      2.1              2.3

In [16]:
# trian model on scaled data and unscaled data and compare the accuracy score

model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy_score(y_test, y_pred)

0.9125

In [18]:
# pirnt accuracy score for scaled data and unscaled data
print("Accuracy score for unscaled data: ", accuracy_score(y_test, y_pred))
print("Accuracy score for scaled data: ", accuracy_score(y_test, model.predict(x_test_scaled)))

Accuracy score for unscaled data:  0.925
Accuracy score for scaled data:  0.925