# MISSING VALUES OF CATAGORICAL AND NUMERICAL VALUES

## Random Imputation

In [39]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [40]:
# upload titanic dataset only use age, fare, survived
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', usecols=['Survived', 'Age', 'Fare'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [41]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [42]:
x = df.drop(columns='Survived')
y = df['Survived']

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [44]:
x_train['age_imputed'] = x_train['Age']
x_test['age_imputed'] = x_test['Age']

In [45]:
x_train.head()

      Age     Fare  age_imputed
331  45.5  28.5000         45.5
733  23.0  13.0000         23.0
382  32.0   7.9250         32.0
704  26.0   7.8542         26.0
813   6.0  31.2750          6.0

In [46]:
x_test.head()

      Age     Fare  age_imputed
709   NaN  15.2458          NaN
439  31.0  10.5000         31.0
840  20.0   7.9250         20.0
720   6.0  33.0000          6.0
39   14.0  11.2417         14.0

In [47]:
x_train['age_imputed'] = x_train['age_imputed'].fillna(pd.Series(x_train['Age'].dropna().sample(x_train['Age'].isnull().sum()).values))
x_test['age_imputed'] = x_test['age_imputed'].fillna(pd.Series(x_test['Age'].dropna().sample(x_test['Age'].isnull().sum()).values))

In [48]:
x_train['Age'].dropna().sample(x_train['Age'].isnull().sum()).values

array([28.  , 29.  , 24.  , 24.  , 17.  , 21.  , 45.  , 33.  , 13.  ,
       36.  , 26.  ,  9.  , 51.  , 42.  , 34.  , 23.  , 21.  , 21.  ,
       32.  , 29.  , 29.  , 44.  , 46.  , 24.  , 29.  ,  1.  , 24.  ,
       24.  , 22.  , 62.  , 34.  ,  8.  , 32.  , 21.  , 23.  , 18.  ,
       37.  , 25.  , 54.  , 60.  , 32.  , 48.  , 32.  , 22.  , 31.  ,
       45.  , 18.  , 49.  , 34.  , 21.  , 33.  , 36.  , 34.5 ,  0.92,
       31.  , 19.  , 35.  , 38.  , 14.  , 25.  , 28.  , 39.  , 27.  ,
        0.42, 32.  ,  7.  , 22.  , 19.  , 17.  , 19.  ,  2.  , 42.  ,
       28.  , 29.  , 50.  , 57.  , 41.  , 31.  , 42.  , 36.  , 47.  ,
       33.  , 15.  , 39.  ,  4.  , 25.  , 58.  , 26.  , 74.  , 35.  ,
        8.  , 24.  , 33.  ,  3.  , 44.  , 56.  , 16.  , 42.  , 26.  ,
       29.  , 27.  , 18.  , 21.  ,  2.  , 17.  , 20.  , 39.  , 31.  ,
       19.  , 39.  , 16.  , 18.  , 23.  , 41.  , 31.  ,  9.  , 26.  ,
       45.  , 19.  , 29.  , 35.  , 44.  , 34.  , 24.  , 24.  , 25.  ,
       32.  , 26.  , 22.  , 42.  , 18.  , 33.  , 31.  , 24.  , 30.  ,
       25.  , 33.  , 44.  , 16.  , 19.  ])

In [49]:
x_train

      Age      Fare  age_imputed
331  45.5   28.5000         45.5
733  23.0   13.0000         23.0
382  32.0    7.9250         32.0
704  26.0    7.8542         26.0
813   6.0   31.2750          6.0
..    ...       ...          ...
106  21.0    7.6500         21.0
270   NaN   31.0000          NaN
860  41.0   14.1083         41.0
435  14.0  120.0000         14.0
102  21.0   77.2875         21.0

[712 rows x 3 columns]

In [ ]:
sns.displot(x_train['age_imputed'], label='imputed', hist=False)
sns.displot(x_train['Age'], label='Original', hist=False)
plt.legend()
plt.show()