# HANDLING DATE AND TIME

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [ ]:
# import both dataset
df1 = pd.read_csv('date.csv')
df2 = pd.read_csv('time.csv')

In [5]:
df1.head()

   ID       Date        Day     Month  Year
0   1 2025-01-15  Wednesday   January  2025
1   2 2025-02-20   Thursday  February  2025
2   3 2025-03-05  Wednesday     March  2025
3   4 2025-04-12   Saturday     April  2025
4   5 2025-05-25     Sunday       May  2025

In [11]:
# convert date colum into date_time
df1['Date'] = pd.to_datetime(df1['Date'])

In [14]:
df1['date_year'] = df1['Date'].dt.year
# now for month
df1['date_month_no'] = df1['Date'].dt.month
# now for day
df1['date_day_no'] = df1['Date'].dt.day

In [15]:
df1.head()

,ID,Date,Day,Month,Year,date_year,date_month_no,date_day_no
0,1,2025-01-15,Wednesday,January,2025,2025,1,15
1,2,2025-02-20,Thursday,February,2025,2025,2,20
2,3,2025-03-05,Wednesday,March,2025,2025,3,5
3,4,2025-04-12,Saturday,April,2025,2025,4,12
4,5,2025-05-25,Sunday,May,2025,2025,5,25